TrajectoryPlannerROS:
  max_vel_x: 0.1
  min_vel_x: 0
  max_vel_y: 0.1
  min_vel_y: 0
  max_vel_theta: 0.17
  min_in_place_vel_theta: 0

  acc_lim_theta: 0.17
  acc_lim_x: 0.1
  acc_lim_y: 0.1

  holonomic_robot: true
  